name: betway
base_url: https://www.betway.com
browser_path: /usr/bin/chrome
username: user1
password: pass1
region: KE
selectors:
  login:
    username_input: input#username
    password_input: input#password
    login_button: button#login
  session:
    logout_button: button#logout
    session_user_info: div#userInfo
  event_search:
    sport_dropdown: select#sport
    date_picker: input#date
    search_button: button#search
    event_results: div#eventResults
    event_item: div.event-item
    event_title: div.event-title
    event_team: div.event-team
  odds_selector:
    moneyline: div.match-result
    spread: div.over-under
    totals: div.point-spread
    odds_dropdown: select#odds
  bet_slip:
    add_button: button#addToBetSlip
    remove_button: button#removeBetSlipItem
    stake_input: input#stake
    calculate_button: button#calculate
    clear_button: button#clearBetSlip
    potential_payout: div#potentialPayout
    bet_slip_item: div.bet-slip-item
  live_betting:
    live_betting_button: button#liveBetting
    odds_change_indicator: div.odds-change-indicator
    live_event_item: div.live-event-item
    live_score: div.live-score
    live_odd_selector: div.live-odd-selector
    live_event: div.live-event
    in_play_bet_button: ""
  line_movement:
    line_change_indicator: div.line-change-indicator
    odds_history: div.odds-history
    betting_lines: div.betting-lines
  filter_options:
    sport_dropdown: select#sportFilter
    market_type_dropdown: select#marketTypeFilter
    time_filter: input#timeFilter
    reset_filters_button: button#resetFilters
  balance_tracker:
    balance_page_link: a#accountBalanceLink
    balance_container: div.balance-summary
    current_balance_field: span.current-balance
    available_balance_field: span.available-balance
    pending_withdrawals_field: span.pending-withdrawals
    transaction_row_selector: div.transaction-row
    transaction_type_column: div.transaction-row .type
    transaction_amount_column: div.transaction-row .amount
    transaction_date_column: div.transaction-row .date
    filter_by_type: select#filterByTransactionType
    filter_by_date: select#filterByDateRange
  bet_confirmation:
    confirm_button: button#confirmBet
    error_message: div#errorMessage
    success_message: div#successMessage
    bet_summary: div#betSummary
  bet_history:
    history_page_link: a#betHistoryLink
    bet_row_selector: div.bet-row
    event_column: div.bet-row .event
    stake_column: div.bet-row .stake
    outcome_column: div.bet-row .outcome
    filter_by_result: select#filterByResult
    filter_by_market: select#filterByMarket
  promotions:
    promotion_banner: div#promotionBanner
    redeem_button: button#redeemPromo
    promo_code_input: input#promoCode
    apply_promo_button: button#applyPromo
  cash_out:
    cash_out_button: button#cashOut
    open_bet: div.open-bet
    cancellable_bet_indicator: div.cancellable-bet
    cashout_offer: div.cashout-offer
    confirm_cashout_button: button#confirmCashout
  notification_center:
    notification_popup: div#notificationPopup
    dismiss_button: button#dismissNotification
    notification_message: div.notification-message
    notification_type: div.notification-type
bet_button: button#placeBet
bet_history: div#betHistory
timeout:
  bet_operation: 30000
  page_load: 5000
  selector_wait: 5000
betting:
  stake: 100
  bet_type: match_result
  odds: 2.5
  team: Team A
  event_id: "12345"
  query: "2023-10-15"
user_credentials:
  username: user1
  password: pass1
